### PR TITLE
[TASK] Deprecated dataServiceProcessor and use dataProcessingService

### LINKED ISSUE #11: Wrong information in Readme
I integrated your extension in a typo3 system and had to fetch that you have a mistake in your readme.

In _Configure the JS Files to be handled by Usercentrics:_ you use the attribute **dataProcessingService**
which causes an error in the frontend of my page.
```txt
Oops, an error occurred!
No valid identifier given for file, please check TypoScript configuration.

More information regarding this error might be available online.
```
The Reason is, that in your function T3G\AgencyPack\Usercentrics\Hooks\PageRendererPreProcess::isValidIdentifier
you are checking the index **dataServiceProcessor**. This is the reason the exception is thrown.

In your last [commit](https://github.com/TYPO3GmbH/ext-usercentrics/commit/fb4e82135f90d1a84db6ab7e2694fa2eda349e3b#diff-04c6e90faac2675aa89e2176d2eec7d8) you changed the readme.

Did you just forget the class or is it really a mistake in the readme?

### PR DESCRIPTION
**Pull request by NeoBlack**
Releases: master
Fix: #11

### CODE REVIEW

File: Classes/Hooks/PageRendererPreProcess.php [hunk 1]
```diff
@@ -122,6 +122,27 @@ protected function isValidId(array $config): bool
 
     protected function isValidIdentifier(array $jsFile): bool
     {
-        return isset($jsFile['dataServiceProcessor']) && is_string($jsFile['dataServiceProcessor']);
+        if (isset($jsFile['dataServiceProcessor'])) {
+            trigger_error(
+                'The settings "dataServiceProcessor" has been marked as deprecated. Use dataProcessingService instead.',
```
Comment (andreaskienast) [inline Classes/Hooks/PageRendererPreProcess.php]: "The setting"

File: Classes/ViewHelpers/ScriptViewHelper.php [hunk 2]
```diff
@@ -62,4 +69,16 @@ public function render(): string
         }
         return '';
     }
+
+    protected function getDataProcessingService(): string
+    {
+        if (isset($this->arguments['dataServiceProcessor'])) {
+            trigger_error(
+                'The argument "dataServiceProcessor" of the ' . self::class . ' ViewHelper has been marked as deprecated. Use dataProcessingService instead.',
```
Comment (andreaskienast) [inline Classes/ViewHelpers/ScriptViewHelper.php]: `self::class` contains the suffix "ViewHelper" already.
Proposal:
```
'The argument "dataServiceProcessor" of ' . self::class . ' has been marked as deprecated'
```

**Review by andreaskienast — CHANGES_REQUESTED** [review]

**Review by andreaskienast — APPROVED** [review]

**Review by susannemoog — APPROVED** [review]
